export const marcatori = [
  {
    giocatore: "Cristiano Ronaldo",
    squadra: "🇮🇷 Iran",
    allenatore: "Pres",
    gol: 0,
  },
  {
    giocatore: "Bukayo Saka",
    squadra: "🇮🇷 Iran",
    allenatore: "Pres",
    gol: 0,
  },
  {
    giocatore: "Michael Olise",
    squadra: "🇮🇷 Iran",
    allenatore: "Pres",
    gol: 0,
  },
  {
    giocatore: "Lamine Yamal",
    squadra: "🇬🇭 Ghana",
    allenatore: "Andrea S.",
    gol: 0,
  },
  {
    giocatore: "Jonathan David",
    squadra: "🇬🇭 Ghana",
    allenatore: "Andrea S.",
    gol: 0,
  },
  {
    giocatore: "Omar Marmoush",
    squadra: "🇬🇭 Ghana",
    allenatore: "Andrea S.",
    gol: 0,
  },
  {
    giocatore: "Marcus Thuram",
    squadra: "🇲🇽 Messico",
    allenatore: "Cristian",
    gol: 0,
  },
  {
    giocatore: "Gonçalo Ramos",
    squadra: "🇲🇽 Messico",
    allenatore: "Cristian",
    gol: 0,
  },
  {
    giocatore: "Mikel Oyarzabal",
    squadra: "🇲🇽 Messico",
    allenatore: "Cristian",
    gol: 0,
  },
  {
    giocatore: "Harry Kane",
    squadra: "🇨🇴 Colombia",
    allenatore: "Luigi",
    gol: 0,
  },
  {
    giocatore: "Luis Díaz",
    squadra: "🇨🇴 Colombia",
    allenatore: "Luigi",
    gol: 0,
  },
  {
    giocatore: "Nicolas Jackson",
    squadra: "🇨🇴 Colombia",
    allenatore: "Luigi",
    gol: 0,
  },
  {
    giocatore: "Lautaro Martínez",
    squadra: "🇵🇹 Portogallo",
    allenatore: "Andrea A.",
    gol: 0,
  },
  {
    giocatore: "Darwin Núñez",
    squadra: "🇵🇹 Portogallo",
    allenatore: "Andrea A.",
    gol: 0,
  },
  {
    giocatore: "Leroy Sané",
    squadra: "🇵🇹 Portogallo",
    allenatore: "Andrea A.",
    gol: 0,
  },
  {
    giocatore: "Kylian Mbappé",
    squadra: "🇦🇷 Argentina",
    allenatore: "Erny",
    gol: 0,
  },
  {
    giocatore: "Patrik Schick",
    squadra: "🇦🇷 Argentina",
    allenatore: "Erny",
    gol: 0,
  },
  {
    giocatore: "Kai Havertz",
    squadra: "🇦🇷 Argentina",
    allenatore: "Erny",
    gol: 0,
  },
  {
    giocatore: "Alexander Isak",
    squadra: "🇩🇪 Germania",
    allenatore: "Martin",
    gol: 0,
  },
  {
    giocatore: "Cody Gakpo",
    squadra: "🇩🇪 Germania",
    allenatore: "Martin",
    gol: 0,
  },
  {
    giocatore: "Riyad Mahrez",
    squadra: "🇩🇪 Germania",
    allenatore: "Martin",
    gol: 0,
  },
  {
    giocatore: "Julián Álvarez",
    squadra: "🇨🇼 Curaçao",
    allenatore: "Fava",
    gol: 0,
  },
  {
    giocatore: "Raphinha",
    squadra: "🇨🇼 Curaçao",
    allenatore: "Fava",
    gol: 0,
  },
  {
    giocatore: "Romelu Lukaku",
    squadra: "🇨🇼 Curaçao",
    allenatore: "Fava",
    gol: 0,
  },
  {
    giocatore: "Erling Haaland",
    squadra: "🇫🇷 Francia",
    allenatore: "Sirty",
    gol: 0,
  },
  {
    giocatore: "Mohamed Salah",
    squadra: "🇫🇷 Francia",
    allenatore: "Sirty",
    gol: 0,
  },
  {
    giocatore: "Viktor Gyökeres",
    squadra: "🇫🇷 Francia",
    allenatore: "Sirty",
    gol: 0,
  },
  {
    giocatore: "Alexander Sørloth",
    squadra: "🇺🇿 Uzbekistan",
    allenatore: "Michel",
    gol: 0,
  },
  {
    giocatore: "Anthony Gordon",
    squadra: "🇺🇿 Uzbekistan",
    allenatore: "Michel",
    gol: 0,
  },
  {
    giocatore: "João Félix",
    squadra: "🇺🇿 Uzbekistan",
    allenatore: "Michel",
    gol: 0,
  },
  {
    giocatore: "Ousmane Dembélé",
    squadra: "🇨🇮 Costa d'Avorio",
    allenatore: "Fabio",
    gol: 0,
  },
  {
    giocatore: "Kenan Yıldız",
    squadra: "🇨🇮 Costa d'Avorio",
    allenatore: "Fabio",
    gol: 0,
  },
  {
    giocatore: "Désiré Doué",
    squadra: "🇨🇮 Costa d'Avorio",
    allenatore: "Fabio",
    gol: 0,
  },
  {
    giocatore: "Lionel Messi",
    squadra: "🇹🇷 Turchia",
    allenatore: "Bruno",
    gol: 0,
  },
  {
    giocatore: "Vinícius Júnior",
    squadra: "🇹🇷 Turchia",
    allenatore: "Bruno",
    gol: 0,
  },
  {
    giocatore: "Heung-min Son",
    squadra: "🇹🇷 Turchia",
    allenatore: "Bruno",
    gol: 0,
  },
];