export const NATIONAL_CODES: Record<string, string> = {
  Algeria: "ALG",
  Argentina: "ARG",
  Australia: "AUS",
  Austria: "AUT",
  Belgio: "BEL",
  Bosnia: "BIH",
  Brasile: "BRA",
  Canada: "CAN",
  Colombia: "COL",
  "Corea del Sud": "KOR",
  "Costa d'Avorio": "CIV",
  Croazia: "CRO",
  Ecuador: "ECU",
  Egitto: "EGY",
  Francia: "FRA",
  Germania: "GER",
  Ghana: "GHA",
  Giappone: "JPN",
  Inghilterra: "ENG",
  Iran: "IRN",
  Marocco: "MAR",
  Messico: "MEX",
  Norvegia: "NOR",
  "Paesi Bassi": "NED",
  Portogallo: "POR",
  "Repubblica Ceca": "CZE",
  "Repubblica Democratica del Congo": "COD",
  Scozia: "SCO",
  Senegal: "SEN",
  Spagna: "ESP",
  "Stati Uniti": "USA",
  Sudafrica: "RSA",
  Svezia: "SWE",
  Svizzera: "SUI",
  Tunisia: "TUN",
  Turchia: "TUR",
  Uruguay: "URU",
  Uzbekistan: "UZB",
};

export function getNationalCode(nazionale?: string | null) {
  if (!nazionale) return "---";
  return NATIONAL_CODES[nazionale] || nazionale.slice(0, 3).toUpperCase();
}